name: Python Tests Runner
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python3_8:
    name: python3.8
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Project
      uses: actions/checkout@v2
    - name: Setup Golang and recompile.so file
      uses: cedrickring/golang-action@1.6.0
      env:
        PROJECT_PATH: "./examples"
      run: |
        go build -o golangCode.so -buildmode=c-shared golangCode.go
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install Dependencies
      run: |
        pip install .
    - name: Run Tests
      run: python tests.py
